redeem and its test
Alcibiades-Capital/valorem-options-contracts pull request #8
Opened 2022-03-24 23:02 UTC by cranium7811

2022-03-24 23:15 UTC, 0xAlcibiades commented
@cranium7811 can you resolve the merge conflicts here, please.

2022-03-24 23:55 UTC, 0xAlcibiades requested changes

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        require(!claimRecord.claimed, "Already Claimed");
This require could come before all the storage access on the option.

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        uint256 balance = ERC1155(address(this)).balanceOf(msg.sender, claimId);
You can just call this.balanceOf, no?

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        require(balance == 1, "no claim token");
This check can come before all the storage access.

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        uint256 tx_amount = (optionRecord.exerciseAmount *
These should be calculated as 2 entirely seperate amounts, and transfered conditionally. There may be either or both of these assets transferred on claim.

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        SafeTransferLib.safeTransfer(
Where is the conditional transfer for the exercise asset?

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        _batchBurn(msg.sender, tokens, amounts);
We don't need a batch burn here, we should only burn the claim.

2022-03-24 23:55 UTC, 0xAlcibiades commented on src/OptionSettlement.sol
> +        amounts[0] = (claim[claimId].amountWritten -
We shouldn't be touching the option token here per se, it doesn't do us any good, just results in another sstore.

2022-03-25 01:37 UTC, cranium7811 commented
created a new PR

2022-03-25 01:37 UTC, closed without merging